Repository Nimtego/ofc, pull requests merged in 2018-07, with the labels that each got.

#9 Readme.md spell mistake fix
  README.md
Labels: reviewing

#15 Update README.md
  README.md
Labels: ready, reviewing

#14 Readme.md spell mistake fix
  README.md
Labels: bug, ready, reviewing

#18 Schematic diagram application
  diagram/schematic_diagram_application.pdf
Labels: ready, reviewing

#20 #12 standard structure a studio
  .gitignore
  .idea/caches/build_file_checksums.ser
  .idea/codeStyles/Project.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/pto6/ofc/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/pto6/ofc/view/OfcListActivity.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ofc2.png
  app/src/main/res/layout/activity_ofc_list.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/example/pto6/ofc/ExampleUnitTest.java
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: enhancement, ready

#22 Template create
  . github/pull_request_template.md
Labels: ready

#28 master, dev branch ci only template
  .circleci/config.yml
Labels: ready

#29 #10 cd
  .circleci/config.yml
Labels: ready
